serviceAccount:
  name: sa-external-dns
  create: true
  annotations:
    azure.workload.identity/client-id: "e8a773b0-e475-4aae-a5b1-507a1a7a72cc"
    azure.workload.identity/tenant-id: "3de73d75-c7d2-4360-9c96-48d3caab11e5"
podLabels:
  azure.workload.identity/use: "true"
serviceMonitor:
  enabled: false
provider: azure
secretConfiguration:
  enabled: true
  mountPath: "/etc/kubernetes/"
  data:
    azure.json: |
      {
        "subscriptionId": "66f26fea-ff43-4f9a-bf6d-e2d18d696616",
        "resourceGroup": "rg-argocd-cluster",
        "useWorkloadIdentityExtension": true
      }
