global:
  logLevel: 3
installCRDs: true
extraArgs:
- --enable-certificate-owner-ref=true
prometheus:
  enabled: false
podLabels:
  app.kubernetes.io/part-of: stage-fleet
  azure.workload.identity/use: 'true'
serviceAccount:
  name: sa-cert-manager
  annotations:
    azure.workload.identity/client-id:  "4d4dc855-2a64-4c68-bcfd-1fc8ba85d6dd"
    azure.workload.identity/tenant-id:  "3de73d75-c7d2-4360-9c96-48d3caab11e5"
