apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app
  namespace: argocd
spec:
  ## https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    # https://argocd-applicationset.readthedocs.io/en/stable/Generators-Matrix/
    - matrix:
        generators:
          ## https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/
          - git:
              repoURL: https://github.com/ishuar/argocd-multi-cluster.git
              revision: main
              files:
                - path: "argocd/envs/**/**/**/demo-app/git-generator-overides.json"
          ## https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/
          - clusters:
              selector:
                matchLabels:
                  app.kubernetes.io/part-of: '{{.environment}}-fleet' ## filter on environment type
                  cluster-region: '{{index .path.segments 4}}'        ## filter on region type
                  cloud-provider: '{{index .path.segments 3}}'        ## filter on cloud type
                  argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      name: 'demo-app-{{index .path.segments 2}}-{{index .path.segments 3}}-{{index .path.segments 4}}'
      labels:
        app.kubernetes.io/component: argocd-application
        cluster-region: '{{index .path.segments 4}}'
        cloud-provider: '{{index .path.segments 3}}'
    spec:
      project: default ## Can use dynamic project name from git file generator. (project shoud be created before hand and can be part of bootstrap)
      sources:
        - repoURL: 'https://github.com/ishuar/argocd-multi-cluster.git'
          targetRevision: main
          path: '{{.path.path}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        ## https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automated-sync-policy
        automated:
          prune: true
          selfHeal: true
        ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#sync-options
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true

